import * from "std/fs"
import { array_contains } from "std/array"

main {
    let tmpdir = $ mktemp -d /tmp/amber-XXXX $ failed {
        echo "Error making directory /tmp/amber-XXXX"
    }
    cd tmpdir
    $ touch test.txt $ failed {
        echo "Error touching test.txt"
    }
    silent $ tar -czf "filename.tar.gz" "{tmpdir}/test.txt" $ failed {
        echo "Error compressing"
    }
    $ rm "test.txt" $ failed {
        echo "Error removing test.txt"
    }
    let package = tmpdir + "/" + "filename.tar.gz"

    file_extract(package, tmpdir) failed {
        echo "Error"
    }

    if dir_exists(tmpdir + "/" + tmpdir) {
        echo "Succeeded"
    }

    trust $ rm -rf "{tmpdir}" $ failed {
        echo "Error removing"
    }
}
